### ISSUE TITLE
Platform "Unable to update entity due to data processing error"

### ISSUE THREAD

**Issue by condacum** [JaccoR/hass-entso-e#167]
The Entsoe platform is unable to update.

I can see the following in the logs: 

_2024-08-30 05:56:48.583 WARNING (MainThread) [custom_components.entsoe.sensor] Unable to update entity due to data processing error: None and error: min() iterable argument is empty
2024-08-30 05:56:48.583 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.time_of_highest_price_today (<class 'custom_components.entsoe.sensor.EntsoeSensor'>) is using state class 'measurement' which is impossible considering device class ('timestamp') it is using; expected None; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/JaccoR/hass-entso-e/issues
2024-08-30 05:56:48.587 WARNING (MainThread) [custom_components.entsoe.sensor] Unable to update entity due to data processing error: None and error: min() iterable argument is empty
2024-08-30 05:56:48.587 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.time_of_lowest_price_today (<class 'custom_components.entsoe.sensor.EntsoeSensor'>) is using state class 'measurement' which is impossible considering device class ('timestamp') it is using; expected None; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/JaccoR/hass-entso-e/issues
2024-08-30 06:00:00.568 WARNING (MainThread) [custom_components.entsoe.sensor] Unable to update entity due to data processing error: None and error: min() iterable argument is empty
2024-08-30 06:00:00.579 WARNING (MainThread) [custom_components.entsoe.sensor] Unable to update entity due to data processing error: None and error: min() iterable argument is empty
2024-08-30 06:00:00.583 WARNING (MainThread) [custom_components.entsoe.sensor] Unable to update entity due to data processing error: None and error: min() iterable argument is empty
2024-08-30 06:00:00.587 WARNING (MainThread) [custom_components.entsoe.sensor] Unable to update entity due to data processing error: None and error: min() iterable argument is empty
2024-08-30 06:00:00.591 WARNING (MainThread) [custom_components.entsoe.sensor] Unable to update entity due to data processing error: None and error: min() iterable argument is empty
2024-08-30 06:00:00.594 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.average_electricity_price_today fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 942, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1300, in async_device_update
    await self.async_update()
  File "/config/custom_components/entsoe/sensor.py", line 134, in async_update
    self._attr_extra_state_attributes = {x: self.coordinator.processed_data()[x] for x in self.coordinator.processed_data() if x not in invalid_keys and x not in existing_entities}
                                                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/entsoe/coordinator.py", line 171, in processed_data
    "min_price": self.get_min_price(filtered_hourprices),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/entsoe/coordinator.py", line 213, in get_min_price
    return min(hourprices.values())
           ^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: min() iterable argument is empty
2024-08-30 06:00:00.599 WARNING (MainThread) [custom_components.entsoe.sensor] Unable to update entity due to data processing error: None and error: min() iterable argument is empty_

I hope this can help solving the issue.

**Comment by micvdh** [comment]
Same issue here, see some more detailed logs: 

2024-08-30 07:03:39.569 DEBUG (MainThread) [custom_components.entsoe.coordinator] Fetching ENTSO-e data
2024-08-30 07:03:39.569 DEBUG (MainThread) [custom_components.entsoe.coordinator] BE
2024-08-30 07:03:42.763 DEBUG (MainThread) [custom_components.entsoe.coordinator] Finished fetching ENTSO-e coordinator data in 3.194 seconds (success: True)
2024-08-30 07:03:42.767 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.engie_current_electricity_market_price (<class 'custom_components.entsoe.sensor.EntsoeSensor'>) is using state class 'measurement' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/JaccoR/hass-entso-e/issues
2024-08-30 07:03:42.773 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.engie_next_hour_electricity_market_price (<class 'custom_components.entsoe.sensor.EntsoeSensor'>) is using state class 'measurement' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/JaccoR/hass-entso-e/issues
2024-08-30 07:03:42.777 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.engie_lowest_energy_price_today (<class 'custom_components.entsoe.sensor.EntsoeSensor'>) is using state class 'measurement' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/JaccoR/hass-entso-e/issues
2024-08-30 07:03:42.781 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.engie_highest_energy_price_today (<class 'custom_components.entsoe.sensor.EntsoeSensor'>) is using state class 'measurement' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/JaccoR/hass-entso-e/issues
2024-08-30 07:03:42.800 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.engie_average_electricity_price_today (<class 'custom_components.entsoe.sensor.EntsoeSensor'>) is using state class 'measurement' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/JaccoR/hass-entso-e/issues
2024-08-30 07:03:42.807 WARNING (MainThread) [custom_components.entsoe.sensor] Unable to update entity due to data processing error: None and error: unsupported operand type(s) for /: 'NoneType' and 'float'
2024-08-30 07:03:42.808 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.engie_current_percentage_of_highest_electricity_price_today (<class 'custom_components.entsoe.sensor.EntsoeSensor'>) is using state class 'measurement' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/JaccoR/hass-entso-e/issues
2024-08-30 07:03:42.815 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.engie_time_of_highest_price_today (<class 'custom_components.entsoe.sensor.EntsoeSensor'>) is using state class 'measurement' which is impossible considering device class ('timestamp') it is using; expected None; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/JaccoR/hass-entso-e/issues
2024-08-30 07:03:42.822 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.engie_time_of_lowest_price_today (<class 'custom_components.entsoe.sensor.EntsoeSensor'>) is using state class 'measurement' which is impossible considering device class ('timestamp') it is using; expected None; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/JaccoR/hass-entso-e/issues

**Comment by firefixmaarten** [comment]
I got it to work again:

- updated HACS to 2.0.0
- installed latest entso-e integration (hacs should notify) https://github.com/JaccoR/hass-entso-e/releases/tag/v0.4.0-beta.3 (not sure this is actually needed)

- setup the SSH addon, set a SSH key (or password if you like).
- ssh into your machine (not using the web-UI) and confirm you are getting in.
- remove the entso-e integration in your integration list (please make sure to note the name and api-key and region.
go back to the ssh session and:
- ha core stop
- cd config/.storage/
- nano core.restore_state (or use vi)
- remove all the entso-e related states
- close the file
- ha core start
Wait a little and login to HA
Add the integration again and it should work ;).

**Comment by martin3000** [comment]
Please update entsoe-py to 0.6.8

**Comment by ljlhouben** [comment]
Ah...and I thought it was my hacking of the 'apexchart'... 
As a newbee, I got the same issue. I only see the data of 'yesterday'.  

I see following errors in the log:
`Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.entsoe.sensor
Bron: custom_components/entsoe/sensor.py:201
integratie: ENTSO-e Transparency Platform (documentatie, problemen)
Eerst voorgekomen: 11:31:22 (1 gebeurtenissen)
Laatst gelogd: 11:31:22

Unable to update entity due to data processing error: None and error: unsupported operand type(s) for /: 'NoneType' and 'float'`

As I thought that I f#cked up my system, I removed all intergrations and re-installed everything (I only pushed the remove and install buttons). As I found that there was a 'beta' release, I updated HA to the latest 0.4.0 beta 3 version. After removing I rebooted, just like after reinstalling. I'm running the software on my Synology NAS in a 'Docker' environment.

**Comment by micvdh** [comment]
Can it be an issue at entsoe API server ?
At my side it resolved automagically shortly after 10:00 BE time, still running v0.3.0

![image](https://github.com/user-attachments/assets/533c8597-5d51-4794-be19-fe69b46dec4b)

**Comment by marple2go** [comment]
After reinstall, the lovelace card still was not working. Looking to the integration, i saw that the identitynames were changed.
After I modified the lovelace APEX chart, i removed entsoe_ out of the identity name, the graph came back again.

**Comment by Roeland54** [comment]
I have found an issue with the state restore logic and implemented a fix. 
I have created a new beta version to test. https://github.com/JaccoR/hass-entso-e/releases/tag/v0.4.0-beta.4
Could you try and report back?

> The entsoe custom component uses a python library called entsoe-py. Please update this entsoe-py library to 0.6.8
> 
> @Roeland54 why is entsoe-py==0.6.2 in the mainfest.json? 0.6.8 does not work? Is it necessary to include the version or is it ok to use "requirements": ["entsoe-py"],

@martin3000 There is a dependency conflict from v0.6.3 and up because it requires pandas==2.2.2 and that creates a conflict with home assistant. Updated to the latest compatible version for now until I have time to find a solution (or someone else does).

**Comment by marple2go** [comment]
It looks like I have the right prices now. I compared the output with the entity of energyzero (another integration)

**Comment by martin3000** [comment]
> There is a dependency conflict from v0.6.3 and up because it requires pandas==2.2.2 and that creates a conflict with home assistant. Updated to the latest compatible version for now until I have time to find a solution (or someone else does).

Sorry, I was sure I updated to 0.6.8 and it was running. But now I see it is only 0.5.8.

**Comment by MarkBovee** [comment]
I get data again with the latest beta. But the format is different somehow so my graphs don’t work.

**Comment by JanBoos** [comment]
I have the same problem. How you install this beta 0.4.0?

**Comment by Roeland54** [comment]
@MarkBovee  Can you provide some more info. Are your entity id's changed? if so from how exactly?

@JanBoos  Go to the integration page in HACS > 3 dot menu top right > redownload > use "Need a different version?" dropdown.

**Comment by JanBoos** [comment]
Beta 0.4.0 werkt bij mij met de juiste prijzen en werkende apex chart.. Ik moest wel een nieuwe api bij entseo aanmaken (eigen probleem?) en een integratie met nieuwe naam.

**Comment by ljlhouben** [comment]
I tried the 0.4.0 beta 4 release and it's working . The information is now updated. Now I can continue to get the correct data displayed in the UI. Great work @Roeland54 🥇

**Comment by condacum** [comment]
Yesterday I was in Beta 0.3.0 and the sensors updated, but no apexchards where filling up with data. This morning I updated to Beta 0.4.0 and also the Apexcharts filled up with data. It seems to work again with correct prices. 
I did not have to change names or API key. 
Tnx for all your work @Roeland54

**Comment by MarkBovee** [comment]
@Roeland54 I recreated the configuration and after some time the charts work again. So it seems fixed now!
