### ISSUE TITLE
Error in commit  b550a58

### ISSUE THREAD

**Issue by Calimerorulez** [JaccoR/hass-entso-e#8]
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/entsoe/__init__.py", line 21, in async_setup_entry
    area = entry.options[CONF_AREA]
KeyError: 'area'
```

**Comment by Calimerorulez** [comment]
Yes, it works again now. Thank you :)
